import { useState } from "react";
import jsPDF from "jspdf";
import logo from "../assets/logo.png";
import { toast } from "react-toastify";

const servicesList = [
  "Website Development",
  "SEO Optimization",
  "Google Business Profile",
  "Resume Services",
  "Social Media Marketing",
  "Logo & Branding Design",
  "Content Writing",
  "YouTube SEO",
  "Instagram Growth",
  "E-commerce Store Setup",
  "Landing Page Design",
  "Google Ads / PPC",
];

export default function Agreement() {
  const [form, setForm] = useState({
    name: "",
    phone: "",
    services: [],
    signature: "",
  });

  const [pdfUrl, setPdfUrl] = useState(null);

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const toggleService = (service) => {
    setForm((prev) => {
      const exists = prev.services.includes(service);
      return {
        ...prev,
        services: exists
          ? prev.services.filter((s) => s !== service)
          : [...prev.services, service],
      };
    });
  };

  const generatePDF = () => {
    const doc = new jsPDF();

    // 🟡 WATERMARK (CENTER)
    doc.setGState(new doc.GState({ opacity: 0.08 }));
    doc.addImage(logo, "PNG", 55, 90, 100, 60);
    doc.setGState(new doc.GState({ opacity: 1 }));

    // 🔵 HEADER
    doc.addImage(logo, "PNG", 20, 10, 25, 15);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("SOFTGENZ", 50, 18);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Freelance Digital Services", 50, 24);
    doc.setTextColor(0);

    // 🔵 TITLE
    doc.setFontSize(14);
    doc.text("SERVICE AGREEMENT", 105, 40, { align: "center" });
    doc.line(20, 45, 190, 45);

    // 🔵 DETAILS
    doc.setFontSize(11);
    doc.text(`Client Name: ${form.name}`, 20, 60);
    doc.text(`Phone Number: ${form.phone}`, 20, 70);
    doc.text(`Services: ${form.services.join(", ")}`, 20, 80);

    // 🔵 AGREEMENT TEXT
    const agreementText = `
This Service Agreement is made between ${form.name} and SOFTGENZ. By submitting this form, ${form.name} agrees to engage SOFTGENZ for the requested service under the terms outlined below.

I agree to provide accurate and complete information regarding the project requirements. SOFTGENZ will make every effort to deliver the requested service within a reasonable timeframe depending on the complexity and scope of the work.

I understand and agree that payment must be made either partially or in full before the final delivery of the project. Any additional features or modifications requested after the initial agreement may result in additional charges.

SOFTGENZ provides limited revisions based on the type of service selected. Once the project work has commenced, no refunds will be issued under any circumstances.

I acknowledge that delays caused due to lack of communication, delayed content submission, or third-party services are not the responsibility of SOFTGENZ.

By signing this agreement, I confirm that I have read, understood, and agreed to all terms and conditions mentioned in this document. This agreement is legally binding and valid without a physical signature.
`;

    const paragraphs = agreementText.split("\n");

    let y = 95;

    paragraphs.forEach((para) => {
      if (para.trim() === "") return;

      const lines = doc.splitTextToSize(para.trim(), 170);
      doc.text(lines, 20, y);

      y += lines.length * 7 + 4;
    });

    // 🔵 SIGNATURES
    y += 10;

    // CLIENT
    doc.text("Client Signature:", 20, y);
    doc.line(20, y + 10, 80, y + 10);
    doc.text(form.signature, 20, y + 8);

    // COMPANY
    doc.text("For SOFTGENZ:", 120, y);
    doc.line(120, y + 10, 180, y + 10);
    doc.text("Authorized Signatory", 120, y + 8);

    y += 25;

    doc.text("Date:", 20, y);
    doc.text(new Date().toLocaleDateString(), 40, y);

    // 🔴 STAMP BOX
    const stampX = 110;
    const stampY = y - 40;

    doc.setDrawColor(40, 70, 160);
    doc.setLineWidth(1.5);
    doc.rect(stampX, stampY, 80, 40);

    doc.setTextColor(40, 70, 160);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("SOFTGENZ", stampX + 40, stampY + 10, {
      align: "center",
    });

    doc.setFontSize(10);
    doc.text("SERVICE AGREEMENT", stampX + 40, stampY + 18, {
      align: "center",
    });

    doc.setFontSize(9);
    doc.text(new Date().toLocaleDateString(), stampX + 40, stampY + 26, {
      align: "center",
    });

    doc.text("SIGN:", stampX + 8, stampY + 34);
    doc.line(stampX + 25, stampY + 34, stampX + 70, stampY + 34);

    doc.setFont("helvetica", "bold");
    doc.text("ROSHINTH SOJAN", stampX + 25, stampY + 32);

    doc.setTextColor(0);

    // 🔵 FOOTER
    doc.setFontSize(9);
    doc.text(
      "This document is digitally generated by SOFTGENZ and is valid without physical signature.",
      105,
      285,
      { align: "center" }
    );

    // PREVIEW
    const blob = doc.output("blob");
    const url = URL.createObjectURL(blob);
    setPdfUrl(url);
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    if (form.services.length === 0) {
      toast.error("Select at least one service");
      return;
    }

    generatePDF();
  };

  return (
    <div className="relative min-h-screen bg-[#030303] text-[#f8fafc] px-6 py-16 sm:py-24 overflow-hidden font-sans">
      {/* 🌌 Background ambient gradient blobs */}
      <div className="absolute top-0 left-1/4 w-[600px] h-[600px] bg-blue-600/5 rounded-full blur-[140px] pointer-events-none -translate-y-1/2"></div>
      <div className="absolute bottom-0 right-1/4 w-[600px] h-[600px] bg-purple-600/5 rounded-full blur-[140px] pointer-events-none translate-y-1/2"></div>

      <div className="relative z-10 max-w-3xl mx-auto animate-fade-in">
        
        {/* Header */}
        <div className="text-center mb-12">
          <span className="px-3 py-1 text-xs font-semibold tracking-wider uppercase text-blue-400 bg-blue-400/10 rounded-full border border-blue-400/20">
            Legal & Terms
          </span>
          <h1 className="text-4xl font-extrabold font-outfit text-white mt-4">
            Service Agreement
          </h1>
          <p className="text-slate-400 mt-2 text-sm">
            Generate and authorize your SOFTGENZ service engagement.
          </p>
        </div>

        {/* 📜 TERMS & CONDITIONS BOX */}
        <div className="
          bg-white/[0.01] border border-white/[0.05] p-8 rounded-3xl mb-10 text-sm text-slate-300 leading-relaxed shadow-xl
          backdrop-blur-md relative overflow-hidden
        ">
          <div className="absolute top-0 right-0 w-24 h-24 bg-blue-500/5 rounded-full blur-2xl"></div>
          
          <h3 className="text-white font-bold font-outfit mb-4 text-lg flex items-center gap-2">
            <svg className="w-5 h-5 text-blue-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
            </svg>
            Agreement Terms & Conditions
          </h3>
          
          <p className="mb-4 text-slate-400">
            This Service Agreement is made between <span className="text-blue-400 font-bold">{form.name || "___(Client Name)___"}</span> and SOFTGENZ.
            By submitting this form, the Client agrees to engage SOFTGENZ under the terms below:
          </p>
          
          <ul className="space-y-3.5 mb-6 text-slate-400">
            <li className="flex items-start gap-3">
              <span className="mt-1 flex-shrink-0 w-1.5 h-1.5 rounded-full bg-blue-500"></span>
              <span>I agree to provide accurate and complete information regarding the project requirements. SOFTGENZ will make every effort to deliver the requested service within a reasonable timeframe.</span>
            </li>
            <li className="flex items-start gap-3">
              <span className="mt-1 flex-shrink-0 w-1.5 h-1.5 rounded-full bg-blue-500"></span>
              <span>I understand that payment must be made either partially or in full before final delivery. Any additional features requested after this agreement may result in additional charges.</span>
            </li>
            <li className="flex items-start gap-3">
              <span className="mt-1 flex-shrink-0 w-1.5 h-1.5 rounded-full bg-blue-500"></span>
              <span>SOFTGENZ provides limited revisions based on the selected service. Once project work has commenced, no refunds will be issued under any circumstances.</span>
            </li>
            <li className="flex items-start gap-3">
              <span className="mt-1 flex-shrink-0 w-1.5 h-1.5 rounded-full bg-blue-500"></span>
              <span>I acknowledge that delays caused due to lack of communication, delayed content submission, or third-party services are not the responsibility of SOFTGENZ.</span>
            </li>
          </ul>
          
          <p className="text-xs text-slate-500 italic border-t border-white/[0.05] pt-4">
            * By generating this agreement, you acknowledge and accept all terms listed above.
          </p>
        </div>

        {/* FORM */}
        <form onSubmit={handleSubmit} className="space-y-6 bg-white/[0.01] border border-white/[0.05] p-8 rounded-3xl backdrop-blur-md">
          
          <div className="grid gap-6 sm:grid-cols-2">
            <div className="space-y-2">
              <label className="text-xs font-semibold text-slate-400 ml-1">Full Name</label>
              <input 
                name="name" 
                placeholder="Client name" 
                value={form.name}
                onChange={handleChange} 
                className="input-ultra" 
                required 
              />
            </div>
            
            <div className="space-y-2">
              <label className="text-xs font-semibold text-slate-400 ml-1">Phone Number</label>
              <input 
                name="phone" 
                placeholder="Contact number" 
                value={form.phone}
                onChange={handleChange} 
                className="input-ultra" 
                required 
              />
            </div>
          </div>

          {/* MULTI SELECT */}
          <div className="space-y-3">
            <label className="text-xs font-semibold text-slate-400 ml-1 block">Select Services Under Engagement</label>
            <div className="flex flex-wrap gap-2.5">
              {servicesList.map((s, i) => {
                const active = form.services.includes(s);
                return (
                  <button
                    type="button"
                    key={i}
                    onClick={() => toggleService(s)}
                    className={`px-4 py-2.5 rounded-xl text-xs font-medium border transition duration-200 ${
                      active
                        ? "bg-blue-600/10 border-blue-500 text-blue-400 shadow-[0_0_15px_rgba(59,130,246,0.1)]"
                        : "bg-white/[0.01] border-white/[0.05] text-slate-400 hover:border-slate-700 hover:text-white"
                    }`}
                  >
                    {s}
                  </button>
                );
              })}
            </div>
          </div>

          <div className="space-y-2">
            <label className="text-xs font-semibold text-slate-400 ml-1">Signature Authorization</label>
            <input
              name="signature"
              placeholder="Type your full name as digital signature"
              value={form.signature}
              onChange={handleChange}
              className="input-ultra"
              required
            />
            <p className="text-[11px] text-slate-500 ml-1">
              Typing your name acts as an electronic signature under applicable IT laws.
            </p>
          </div>

          <button className="btn w-full mt-4">
            <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2.5">
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            Generate Agreement PDF
          </button>

        </form>
      </div>

      {/* PREVIEW MODAL */}
      {pdfUrl && (
        <div className="fixed inset-0 bg-black/80 flex justify-center items-center z-50 p-4 backdrop-blur-md animate-fade-in">
          <div className="bg-[#09090b] border border-white/[0.08] w-full max-w-4xl h-[90vh] flex flex-col rounded-3xl shadow-2xl overflow-hidden animate-slide-up">

            <div className="flex justify-between items-center px-6 py-4 border-b border-white/[0.08]">
              <h2 className="text-lg font-bold font-outfit text-white">Agreement Preview</h2>
              <button 
                onClick={() => setPdfUrl(null)}
                className="p-1.5 rounded-full hover:bg-white/[0.05] transition text-slate-400 hover:text-white"
              >
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>

            <iframe src={pdfUrl} className="flex-1 w-full bg-neutral-900 border-none" title="Agreement PDF Preview" />

            <div className="flex justify-end gap-3 p-4 border-t border-white/[0.08] bg-[#050507]">
              <button
                onClick={() =>
                  document.querySelector("iframe").contentWindow.print()
                }
                className="px-5 py-2.5 rounded-xl border border-white/[0.08] hover:bg-white/[0.05] text-sm font-semibold transition"
              >
                Print
              </button>

              <a href={pdfUrl} download={`${form.name.toLowerCase().replace(/\s+/g, "-")}-agreement.pdf`} className="btn w-auto px-6">
                Download PDF
              </a>
            </div>

          </div>
        </div>
      )}
    </div>
  );
}
